# Generated by Django 4.2.4 on 2023-09-07 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_Name', models.CharField(max_length=50)),
                ('teacher_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_Name', models.CharField(max_length=50)),
                ('stud_Age', models.IntegerField()),
                ('stud_Email', models.EmailField(max_length=254)),
                ('stud_Class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.class')),
            ],
        ),
    ]
